- mkdocs.yml
This setting in `mkdocs.yml` adds links that you can click/share next to each section header in the docs site.
```
markdown_extensions:
- toc:
permalink: true
```
> put links next to section headers in docs site

- src/autolabel/models/openai.py
- tests/unit/llm_test.py
Support for gpt-3.5-turbo-0613, gpt-3.5-turbo-16k and updated pricing for gpt-3.5-turbo models
Tested civil comments with the following model config:
```
"model": {
"provider": "openai",
"name": "gpt-3.5-turbo-0613"
}
```
> add support for new OpenAI models, update pricing

- CONTRIBUTING.md
Before:
```
% pip install .[dev]
zsh: no matches found: .[dev]
```
After:
```
pip install '.[dev]'
Processing /private/tmp/autolabel
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done
Collecting loguru>=0.5.0
Using cached loguru-0.7.0-py3-none-any.whl (59 kB)
Collecting rich>=13.3.5
Using cached rich-13.4.2-py3-none-any.whl (239 kB)
Collecting scipy>=1.10.1
...
```
> Adding single quotes around pip install in CONTRIBUTING.md

- src/autolabel/models/palm.py
- src/autolabel/models/refuel.py
Since `langchain` does not support it, replaced the retry loop with a more robust solution from `tenacity` similar to how it is already implemented in `RefuelLLM`. #316
> added retry with tenacity for palm

- src/autolabel/configs/config.py
- src/autolabel/tasks/base.py
- tests/unit/tasks_test.py
If the LLM response does not correspond to a label in the labels list (only for `classification` and `entity_matching` tasks) then we will mark `successfully_labeled` as `False` for the row and print the warning as shown below.
> Check if the LLM label is in the labels list

- src/autolabel/utils.py
- tests/unit/__init__.py
- tests/unit/test_utils.py
Fix bug report https://github.com/refuel-ai/autolabel/issues/349
This PR adds a test case for two possible scenarios
1. when `force` = True, files are overwritten
2. when `force` = False, if files are present, download doesn't take place
> Update get_data and add test case

- src/autolabel/utils.py
Maintaining the same progress bar as before but specifying the #bytes downloaded
> added custom progress bar for get data

- .github/workflows/test.yaml
Previously we were running tests on PR but on the base commit on the target branch. Modified it to run the tests on the commit on the PR merge branch.
Also, the tests should only run when they are targeting main branch.
> Checks should run on PR commits and after push to main branch

- .github/workflows/test.yaml
- pyproject.toml
Since langchain push multiple releases a day, it can break the library. Pinning it to the last working version.
> Pin Langchain to a working version

- src/autolabel/dataset_loader.py
- src/autolabel/labeler.py
We can now load datasets from Huggingface as show below
```python
dataset = load_dataset("lex_glue", "ledgar")
test_dataset = dataset["test"]
test_dataset = map_label_to_string(test_dataset, "label")
test_dataset = test_dataset.rename_column("text", "example")
ledgar_path = Path("../autolabel/examples/ledgar")
with open(ledgar_path / "config_ledgar.json", "r") as f:
config = json.load(f)
if "few_shot_examples" in config["prompt"] and isinstance(config["prompt"]["few_shot_examples"], str):
config["prompt"]["few_shot_examples"] = str(ledgar_path / config["prompt"]["few_shot_examples"])
agent = LabelingAgent(config)
agent.plan(test_dataset, max_items=8)
agent.run(test_dataset, max_items=8)
```
> added support for hugging face datasets

- .github/workflows/black.yaml
- src/autolabel/database/engine.py
Previously we were running the formatting checks on PR but on the base commit on the target branch. Modified it to run formatting checks on the commit on the PR branch.
> Black formatting checks to run on PR branch

- pyproject.toml
- src/autolabel/models/__init__.py
- src/autolabel/models/cohere.py
- src/autolabel/schema.py
Added [Cohere](https://cohere.com/) support that currently only supports the generation models, defaulting to `command`. To use it, set `config["model"]["provider"]` to `cohere`.
> added cohere support

- src/autolabel/few_shot/__init__.py
- src/autolabel/few_shot/label_diversity_example_selector.py
- src/autolabel/few_shot/vector_store.py
- src/autolabel/labeler.py
- src/autolabel/schema.py
Currently, we order the examples grouped by label, but might want to randomize the order of the selected examples.
> Support example selection using label diversity by random and by semantic similarity

- src/autolabel/models/anthropic.py
- src/autolabel/models/base.py
- src/autolabel/models/cohere.py
- src/autolabel/models/hf_pipeline.py
- src/autolabel/models/openai.py
- src/autolabel/models/palm.py
If the batch fails, simply splits the batch into the individual prompts and then retries them.
> added individual retrying for failed batches

- src/autolabel/schema.py
- src/autolabel/tasks/multilabel_classification.py
- src/autolabel/tasks/question_answering.py
- src/autolabel/tasks/utils.py
- tests/unit/tasks_test.py
`compute_f1` now takes in the entire list of gt labels and llm labels instead of just one at a time. The binarization is also done in `compute_f1` for multilabel classification. This directly addresses #409.
> consolidate compute f1 to single function in utils

- src/autolabel/few_shot/__init__.py
- src/autolabel/few_shot/vector_store.py
- src/autolabel/labeler.py
Now autolabel caches the embeddings when `cache=True` in the same database where task runs are cached. This resolves the need to recompute all the embeddings every time.
This directly addresses #396
> cache embeddings in vector store

- docs/guide/accuracy/chain-of-thought.md
- src/autolabel/labeler.py
- src/autolabel/schema.py
- src/autolabel/tasks/base.py
Currently, the llm explanation is not exposed to the user. This PR adds explanations to LLMAnnotation and the output dataframe allowing users to see the explanation for a label if chain of thought is enabled
Address #460
> Add llm explanation to output dataframe

- src/autolabel/models/palm.py
- tests/unit/llm_test.py
Previously, we were not calculating the output costs of the PALM model. Added a default `max_output_tokens` param and output token calculation into `get_cost`.
> added output cost calculation to PaLM get_cost

- src/autolabel/tasks/classification.py
- src/autolabel/tasks/entity_matching.py
- src/autolabel/tasks/multilabel_classification.py
- src/autolabel/tasks/question_answering.py
- src/autolabel/tasks/utils.py
Currently, we calculate metrics like accuracy and F1 on the entire dataset including unlabeled examples. This leads to incorrect numbers in the case the dataset has some labeled datapoints interspersed with unlabeled examples. This PR filters unlabeled examples before doing metric calculation.
Closes #467
> Fix metric calculation for unlabeled datapoints

- src/autolabel/few_shot/__init__.py
This caused an error as some algorithms did not expect a `cache` kwarg.
> fixed adding cache argument to certain algorithms

- src/autolabel/models/hf_pipeline.py
Added support for causal LMs such as [open llama](https://huggingface.co/openlm-research/open_llama_3b), [gpt2](https://huggingface.co/gpt2), and [Llama 2](https://ai.meta.com/llama/).
> Added causal LM support

- src/autolabel/confidence.py
- src/autolabel/labeler.py
- src/autolabel/models/anthropic.py
- src/autolabel/models/base.py
- src/autolabel/models/cohere.py
- src/autolabel/models/hf_pipeline.py
- src/autolabel/models/openai.py
- src/autolabel/models/palm.py
- src/autolabel/models/refuel.py
- src/autolabel/schema.py
- src/autolabel/tasks/base.py
- src/autolabel/tasks/named_entity_recognition.py
- tests/unit/llm_test.py
- Errors have a structure with error type and error message
- Errors sent in addition to text generation
- New RefuelLLMResult which encapsulates text generations, errors and cost
- Confidence calculate now returns a float
- Errors saved along with annotations and saved in the dataframe
> Bubble up errors and clean up error creation

- .github/workflows/black.yaml
- src/autolabel/labeler.py
- src/autolabel/metrics/__init__.py
- src/autolabel/metrics/accuracy.py
- src/autolabel/metrics/auroc.py
- src/autolabel/metrics/base.py
- src/autolabel/metrics/completion_rate.py
- src/autolabel/metrics/f1.py
- src/autolabel/metrics/support.py
- src/autolabel/schema.py
- src/autolabel/tasks/classification.py
- src/autolabel/tasks/entity_matching.py
- src/autolabel/tasks/multilabel_classification.py
- src/autolabel/tasks/named_entity_recognition.py
- src/autolabel/tasks/question_answering.py
- src/autolabel/tasks/utils.py
- src/autolabel/utils.py
- tests/unit/llm_test.py
- tests/unit/tasks_test.py
- This allows separation of metric calculation from all tasks
- Users can define new additional metrics as classes which can be run every time the model runs
- AUROC calculation now does not return thresholds
- Thresholding logic removed from all tasks - users can request the values at specific thresholds using the output object, or agent.report can show only the thresholds which the user should care about
- Allow specifying custom metrics
> Metric calculation as a separate class

- src/autolabel/configs/config.py
- src/autolabel/configs/schema.py
- src/autolabel/models/hf_pipeline.py
- src/autolabel/models/openai.py
Added logit bias for `huggingface_pipeline` models which can be enabled by settings `logit_bias` to `True` in the model config (just like `openai`)
> added logit bias for huggingface

- src/autolabel/cli/main.py
- `debug` level can be used by `--debug` or `-vv`
- `info` level can be used by `--info` or `-v`
- `warning` level is used by default
- `error` level can be used by `--error` or `-q`
- `critical` level can be used by `--critical` or `-qq`
> Added configurable log level to the CLI

- src/autolabel/cli/config.py
Recently turned logit bias into a float (instead of a boolean) in #495 so the CLI must be updated accordingly. Additionally, previously the CLI only took in strings as model param values. This PR changes that so the CLI can automatically detect booleans, integers, and floats, defaulting to strings when it satisfies none of the others.
> CLI Logit Bias and Model Params Fix

- src/autolabel/__init__.py
- src/autolabel/labeler.py
- tests/unit/dummy_test.py
- tests/unit/test_config.py
- tests/unit/test_data_loading.py
Currently we can pass a dict or string to the Labeling Agent.
This PR will change the LabelingAgent to accept an AutolabelConfig object as an input (to be consistent with the input to the dataset object)
```
from autolabel import LabelingAgent, AutolabelConfig, AutolabelDataset
config = AutolabelConfig('config.json')
dataset = AutolabelDataset('test.csv', config)
agent = LabelingAgent(config)
```
> Accept config in LabelingAgent

- docs/guide/transforms/pdf_transform.md
- docs/guide/transforms/webpage_transform.md
Just wanted to make sure that both of the transform documentation pages are the same format.
> edited pdf transform documentation for consistency

- src/autolabel/dataset/dataset.py
- src/autolabel/labeler.py
- src/autolabel/metrics/auroc.py
- Allow passing custom example selectors which extend the BaseExampleSelector interface
- Fix AUROC when only class is present
> Fix AUROC Bug and allow custom Example Selectors

- src/autolabel/labeler.py
- Currently when the agent starts it checks the database to make sure the same task has not been run before
- However, sometimes we may preview the same task twice
- This currently leads to blocking where we ask the user a question which is not possible to answer inside a script
> Make task management optional

- src/autolabel/dataset/dataset.py
Was running into an issue running dataset.eval() because the annotations column doesn't exist in the output dataframe. Added it in this PR.
> Add annotations column in output dataframe

- src/autolabel/cli/config.py
- src/autolabel/labeler.py
- src/autolabel/utils.py
If the `run` method was stopped by kill signal while a progress bar was being displayed, the next time the `run` method would be run would result in the error `LiveError: Only one live display may be active at once`. This was fixed by setting self.console to Console(quiet=not console_output) instead of writing an if statement whenever printing output.
Additionally, when generating synthetic datasets, the index would repeat for every label (0, 1, 2, 0, 1, 2, ...) when we simply want the index to be a sequence from 0 to n-1. This was fixed by setting `ignore_index` to `True` when concatenating dataframes. A progress bar was also added for generating synthetic datasets.
> fix bugs for kill signal and indexing

- src/autolabel/database/engine.py
- src/autolabel/dataset/dataset.py
- Remove limit from concurrent read requests to sqlite
- Record the prompt that was sent to the model for every labeling run
> Increase pool size and record prompts after labeling

- src/autolabel/configs/config.py
- src/autolabel/configs/schema.py
- src/autolabel/few_shot/label_selector.py
- src/autolabel/labeler.py
- src/autolabel/tasks/classification.py
New option to filter labels_list by similarity to input example.
Two new optional fields are now present in prompt_config schema:
```
"label_selection": true,
"label_selection_count": 10
```
> Better support for classification tasks with large number of label classes

- src/autolabel/few_shot/vector_store.py
Resolves #579 caused by inconsistent model_name attribute in VertexAIEmbeddings class.
> Change embedding model attribute's name in vector store wrapper

- src/autolabel/dataset/dataset.py
cases where labeling fails, the llm label is `NO_LABEL` and not a dict. need to account for this case inside process_labels
> process labels for attribute extraction when llm does not return a valid response

- pyproject.toml
- src/autolabel/confidence.py
- src/autolabel/configs/config.py
- src/autolabel/labeler.py
- src/autolabel/schema.py
In this PR, we will chunk confidence prompts in order to support getting confidence from a model having context length smaller than the context length supported by the generation model. We do this by chunking the document into smaller chunks and sending the prompt along with the smaller chunks of the document. we support multiple aggregation functions over the confidence chunks. 
For extraction, max makes more sense than mean which might make more sense for a classification task
> Chunking for confidence if context exceeds context length

- src/autolabel/confidence.py
- src/autolabel/labeler.py
For attribute extraction task, when the LLM output is not a valid json, the confidence computation fails because of list index out of range exception. Fixing that and also blank catching confidence calculation errors in labeling agent.
> Handle confidence calculation when LLM output is not parsed correctly

- src/autolabel/configs/config.py
Set's explanation column's default value back to `None`.
> Set explanation column default back to None

- pyproject.toml
- src/autolabel/labeler.py
- src/autolabel/models/base.py
- src/autolabel/models/palm.py
- src/autolabel/models/refuel.py
- src/autolabel/tasks/attribute_extraction.py
- src/autolabel/tasks/base.py
- src/autolabel/tasks/classification.py
- src/autolabel/tasks/entity_matching.py
- src/autolabel/tasks/multilabel_classification.py
- src/autolabel/tasks/named_entity_recognition.py
- src/autolabel/tasks/question_answering.py
Adding default max tokens for all models. Ensures that prompts are always trimmed to fit in the input context of the provided model.
Ran banking.ipynb locally with and without examples that exceeded 3250 tokens for the refuel llm model.
> Adding support for trimming prompt based on max context

- docs/guide/overview/getting-started.md
- docs/guide/resources/refuel_datasets.md
Minor broken link fixes
Seems like the issues come because of a revamp of the representation of the docs which now requires all links to have a `autolabel/*` format. 
Future fix - 
- Revamping all of such links. Typically it is better to have relative links like `guide/resources/CLI/` instead of `https://docs.refuel.ai/autolabel/guide/resources/CLI/` to ensure backward compatibility.
> Minor broken link fixes

- src/autolabel/tasks/classification.py
- src/autolabel/tasks/entity_matching.py
- src/autolabel/tasks/multilabel_classification.py
- src/autolabel/tasks/named_entity_recognition.py
Safe string formatting of the task guidelines when keys are not present
Tested with 2 tasks where the task guidelines contains text in curly braces, but the keys are not present when formatting -> Previously this led to an issue, now we safely format the guidelines without these keys.
> Safe formatting for task guidelines when constructing prompts

- src/autolabel/transforms/serp_api.py
- src/autolabel/transforms/serper_api.py
Avoid error when column in query template is not found.
Tested locally with transform with a query template with a non-existent column
> Avoid throwing error if web search query template column is not found

- src/autolabel/cli/main.py
closes #693 
Adds output file name as an optional argument to cli command run
> Add output file name as an optional argument to cli command run

- src/autolabel/tasks/attribute_extraction.py
Changing attribute extraction prompt to only produce the necessary keys. Enforcing that certain attributes always exist can be enforced by the user by specifying in task level prompt.
Locally
> Changing default output to produce only necessary attributes

- src/autolabel/transforms/serp_api.py
- src/autolabel/transforms/serper_api.py
Avoid blocking web scrape if a query column doesn't exist in a row. The query template will just not format that query column.
- Improvement
Tested locally without query column in row
> Continue web scrape if query column is missing from row

- src/autolabel/transforms/webpage_transform.py
- tests/unit/transforms/test_webpage_transform.py
We want to keep the connection timeout to a shorter value so in case a url is unreachable, we are able to return quickly instead of waiting for entire 1 min which is the default read/write timeout.
> Add shorter connection timeout for webpage transform

- src/autolabel/labeler.py
Annotation is not serializable. Fixing the logging the same.
> Fix exception logging when confidence score is not computed

- src/autolabel/labeler.py
We already log the exception, so changing the log type to warning instead for the annotation.
> Change log type to warning for confidence errors

- .github/workflows/test.yaml
Using pip cache for caching autolabel dependencies to speed up tests.
> Use cache to speed up building dependencies for tests

- src/autolabel/transforms/webpage_scrape.py
- src/autolabel/transforms/webpage_transform.py
We currently run into errors when scraping certain domains. When we get an error on such requests, we will retry with a proxy to reduce the chance of error.
Tested retry logic with proxy
> Add premium proxy on webpage transform retries

- src/autolabel/task_chain/task_chain.py
We should be using the transform cache if provided for task chaining.
> Set transform cache when using task chaining

- src/autolabel/labeler.py
The log is misleading, since labels list is only relevant for classification tasks.
Removing log
> Misleading log for non-classification tasks

- src/autolabel/models/openai.py
Currently, the default query params gets modified in a single instantiation of a LabelingAgent. This leads to issues when using the same LabelingAgent for multiple different LLM calls (for instance, when labeling and then generating an explanation, where we want to have different LLM config for both). This was leading to using an incorrect LLM config for the explanation generation LLM call.
Tested locally
> Don't modify default query params directly

- src/autolabel/transforms/__init__.py
- src/autolabel/transforms/custom_api.py
- src/autolabel/transforms/schema.py
New custom API transform support
Tested locally
> custom api transform support

- src/autolabel/labeler.py
- src/autolabel/models/openai.py
- src/autolabel/schema.py
- src/autolabel/tasks/attribute_extraction.py
- src/autolabel/tasks/base.py
Return better error messages and types for labeling errors by parsing LLM provider errors for appropriate error types when available. Still use default error types as fallback.
Tested locally
> Return better error messages and types for labeling errors

- src/autolabel/models/openai_vision.py
OpenAI Vision requests are currently hardcoded to have max tokens of 300. Changing this to correctly read from model config
> Max tokens for openai vision from config

- src/autolabel/transforms/serp_api.py
- src/autolabel/transforms/serper_api.py
Serp api query if input columns are empty. Currently, if the inputs are empty i.e None, we send the string None to google. We should probably change that to an empty string by explicitly filtering this dictionary
> Serp api query if input columns are empty

- src/autolabel/transforms/serp_api.py
- src/autolabel/transforms/serper_api.py
We allow web search transforms to go through even if an expected query column is missing (it just doesn't get formatted in the template). So, this should be warning level.
- Nit
> Change severity level to warning

- src/autolabel/confidence.py
Fixes multilabel confidence when there is a new line from the LLM. We ignore all the logprobs before the last \n from the LLM.
locally
> Fixes multilabel confidence when there is a new line from the LLM

- src/autolabel/labeler.py
Filter multilabel confidence keys for llm labels. Currently, the multilabel confidence may be computed for tokens that were filtered out when parsing the llm response. We don't want to include confidence for labels that were filtered out during parsing logic.
Tested confidence key filtering logic
> Filter multilabel confidence keys for llm labels

- src/autolabel/confidence.py
- src/autolabel/tasks/base.py
Handle leading/trailing whitespace for labels leading to missing multilabel confidence scores.
Tested locally
> Handle leading/trailing whitespace for labels

- src/autolabel/transforms/webpage_scrape.py
- src/autolabel/transforms/webpage_transform.py
- src/autolabel/utils.py
- tests/unit/transforms/test_webpage_scrape.py
Validate webpage scrape URLs using regex. The motivation is to avoid making web scrape requests unnecessarily when the URL is invalid. It is possible that there may be some URL's for which this regex match does not validate correctly. However, these cases should be very niche and this change will avoid several unnecessary web scrape requests for a number of cases where the URL is obviously invalid.
Tested locally with common valid and invalid URL's/patterns
> Validate webpage scrape URLs

- src/autolabel/confidence.py
- src/autolabel/labeler.py
- src/autolabel/schema.py
- src/autolabel/tasks/attribute_extraction.py
> Multilabel integration into task chains as attribute extraction 

- src/autolabel/confidence.py
This bug leads to out of index errors - https://refuel-ai.sentry.io/issues/5903416506/?alert_rule_id=14647036&alert_type=issue&notification_uuid=a206b1ca-88a1-485b-b2f9-c6cb3ef899f4&project=4505830328172544&referrer=slack
> Skip adding start/end tuple if key not found

- src/autolabel/tasks/attribute_extraction.py
The issue currently is that if v is an object (e.g. a dict or list), str(v)  just serializes it as a string, but the resulting string might not always a valid json:
s = """{'k': 'v', 'k2': {'inner_k': 'inner_v'}, 'k3': false}"""
json5.loads(s)
{'k': 'v', 'k2': {'inner_k': 'inner_v'}, 'k3': False}
print(json.dumps(json5.loads(s)))
{"k": "v", "k2": {"inner_k": "inner_v"}, "k3": false}
^ this is a valid json
print(str(json5.loads(s)))
{'k': 'v', 'k2': {'inner_k': 'inner_v'}, 'k3': False}
^this is not a valid json
in order to correctly serialize the respons
> Serialize field outputs correctly

- src/autolabel/tasks/attribute_extraction.py
Support few shot for large label taxonomy by just adding to the retrieved labels in case of few shot. This means that lets say we retrieved 10 labels and have few shot set to 5. If the 5 labels are independent to the 10 retrieved labels, we will be sending 15 labels to the attribute_options.
> Support few shot for large label taxonomy

- .pre-commit-config.yaml
- src/autolabel/labeler.py
- src/autolabel/models/__init__.py
- src/autolabel/models/anthropic.py
- src/autolabel/models/base.py
- src/autolabel/models/cohere.py
- src/autolabel/models/google.py
- src/autolabel/models/hf_pipeline.py
- src/autolabel/models/hf_pipeline_vision.py
- src/autolabel/models/mistral.py
- src/autolabel/models/openai.py
- src/autolabel/models/openai_vision.py
- src/autolabel/models/refuelV2.py
- src/autolabel/models/vllm.py
Reusing the tokenizer reduces the latency.
> Pass tokenizer from LabelingAgent to llm

- src/autolabel/tasks/attribute_extraction.py
Sometimes, Claude returns unescaped \n inside the quoted values of a json response. This PR finds the JSON string and replaces all the \n with \\n only within quotes, leaving other \n untouched.
> Fix for JSON mistakes by claude
