src/autolabel/tasks/classification.py, src/autolabel/tasks/entity_matching.py, src/autolabel/tasks/named_entity_recognition.py, src/autolabel/tasks/question_answering.py
=> remove the -inf row with compute confidence

pyproject.toml
Pinned `anthropic` version to avoid breaking changes [here](https://github.com/anthropics/anthropic-sdk-python/releases/tag/v0.3.0)
=> pin anthropic version to avoid breaking changes

src/autolabel/database/engine.py
Fixes https://github.com/refuel-ai/autolabel/issues/413
=> Fix engine path

src/autolabel/labeler.py
=> added check for refuel api key in plan

README.md, src/autolabel/models/openai.py
Fixes #421 
This PR adds a check for the presence of the OPENAI_API_KEY environment variable. Also it fixes a typo in the config.json in the README (and a couple of linting changes).
=> Fix open api key error handling

examples/ledgar/config_ledgar.json, src/autolabel/data_loaders/read_datasets.py
Add `Adjustments` to the `Ledger` config and rmv `Union` duplicacy
=> rmv duplicate and add adjustments to ledger config

src/autolabel/labeler.py
Remove chunk size parameter and default it to 1 where needed.
=> Rmv chunk size

src/autolabel/configs/schema.py, src/autolabel/data_loaders/read_datasets.py, src/autolabel/data_loaders/validation.py, src/autolabel/tasks/base.py, src/autolabel/tasks/named_entity_recognition.py, tests/unit/tasks_test.py
- Allow labeling of cases where the label column is None
- Fix NER bugs
- Allow the AutolabelConfig json schema to have nullable fields instead of strong data types
=> Allow label column to be null for running autolabel

pyproject.toml, src/autolabel/cli/config.py, src/autolabel/cli/main.py
The `autolabel init` would output the file as `[TODO] Enter task name_config.json` instead of `template_config.json`
=> cli file name bugfix

src/autolabel/labeler.py, src/autolabel/utils.py
=> Allow running transforms in Jupyter Notebook using nest_asyncio

docs/guide/overview/getting-started.md
1. Adding AutolabelDataset import from autolabel library
2. Spell correction
=> typo in getting started docs

src/autolabel/transforms/base.py, src/autolabel/transforms/pdf.py, src/autolabel/transforms/webpage_transform.py, tests/unit/transforms/test_webpage_transform.py
=> Transforms: Send only specified output columns in transformed row

src/autolabel/cache/sqlalchemy_transform_cache.py, src/autolabel/data_models/transform_cache.py, src/autolabel/schema.py, src/autolabel/transforms/__init__.py, src/autolabel/transforms/base.py, src/autolabel/transforms/pdf.py, src/autolabel/transforms/schema.py, src/autolabel/transforms/webpage_transform.py, tests/unit/transforms/test_pdf_transform.py, tests/unit/transforms/test_webpage_transform.py
=> Transforms: Add error handling

src/autolabel/labeler.py, src/autolabel/utils.py
Addresses #554 
Changes the input variables to strings when possible and changes to empty strings when not possible
=> Fix example selector with non string inputs

src/autolabel/configs/config.py, src/autolabel/configs/schema.py, src/autolabel/dataset/dataset.py
Addresses Issue #473 
Optionally disable quoting while reading .csv files.
=> Support disable quoting while reading .csv files

src/autolabel/schema.py, src/autolabel/tasks/named_entity_recognition.py
This PR adds support for full named-entity metrics, namely F1 score for strict, exact, partial and entity type match.
=> Support full named-entity level metrics

examples/banking/example_banking.ipynb, examples/craigslist/config_craigslist.json, examples/craigslist/example_craigslist.ipynb, examples/lexical_relation/config_lexical_relation.json, examples/lexical_relation/example_lexical_relation.ipynb, examples/math/config_math.json, examples/math/example_math.ipynb, examples/quoref/config_quoref.json, examples/quoref/example_quoref.ipynb, src/autolabel/tasks/named_entity_recognition.py, src/autolabel/utils.py
This PR adds the following 4 datasets as examples for using autolabel:
1. Craigslist bargains: Given a passage consisting of negotiation between a seller and buyer about sale of an item, classify the item into one of 'housing', 'furniture', 'bike', 'phone', 'car', 'electronics'.
2. Mathdatasets: Given a math question, classify it into algebra, arithmetic, measurement, numbers, and probability. The guidelines for each class are also provided in the instructions.
3. Lexical relation cogalexv: Given two words, classify the relationship between them into one of ANT, HYPER, PART_OF, SYN, RANDOM
4. Read-extract: Given a paragraph, extract the exact substring from the context which answers the question in the prompt.
=> Expanding benchmark

.pre-commit-config.yaml, src/autolabel/cache/__init__.py, src/autolabel/cache/redis_cache.py, src/autolabel/cache/sqlalchemy_confidence_cache.py, src/autolabel/confidence.py, src/autolabel/data_models/__init__.py, src/autolabel/data_models/confidence_cache.py, src/autolabel/labeler.py, src/autolabel/schema.py
Supports caching confidence scores.
=> Cache confidence scores

src/autolabel/confidence.py, src/autolabel/labeler.py, src/autolabel/schema.py, src/autolabel/tasks/attribute_extraction.py, src/autolabel/tasks/base.py, src/autolabel/tasks/classification.py, src/autolabel/tasks/entity_matching.py, src/autolabel/tasks/multilabel_classification.py, src/autolabel/tasks/named_entity_recognition.py, src/autolabel/tasks/question_answering.py
Confidence calculation will now call https://llm.refuel.ai/models/refuelllm/confidence
=> Supporting confidence calculation using RefuelLLM

src/autolabel/confidence.py, src/autolabel/tasks/base.py, src/autolabel/tasks/question_answering.py
Banking - 
Walmart Amazon - 
Sciq -
=> Bringing back RefuelLLM for conf

src/autolabel/confidence.py
Find the tokens in the confidence returned logprobs and use these to make confidence finding more robust
=> parse attribute extraction confidence based on finding tokens

src/autolabel/configs/config.py, src/autolabel/labeler.py, src/autolabel/tasks/attribute_extraction.py
Adding explanation support for attribute extraction
=> Allowing explanation generation for attribute extraction

src/autolabel/tasks/attribute_extraction.py, src/autolabel/tasks/multilabel_classification.py
Ensure the LLM provides explanations for labels with constraints on structure and output length
Improvement to an existing feature
Locally
=> Encourage LLM to provide more succinct explanations

src/autolabel/labeler.py
Fixing the reference errors for the automatic chunking. Few shot examples are also being considered while chunking. However, default tokenizer needs to be switched according to the shift in Refuel-LLM in a followup PR to the LLamaTokenizer
Bug fix (change which fixes an issue)
closes #685
=> fix reference error

src/autolabel/models/refuel.py
Switching from using gpt2 as a proxy tokenizer to the chat model tokenizer that is actually used by refuel llm
=> Pushing refuel llm tokenizer

src/autolabel/tasks/base.py
Trim prompts with the following priority if outside context length: seedset, task guidelines, output guidelines, current labeling example
=> Trim prompt with priority if outside context length

src/autolabel/confidence.py, src/autolabel/models/base.py
Reducing TTL for redis cache from 3 years to 1 week. 
=> Reducing ttl from 3 years to 1 week

src/autolabel/transforms/schema.py, src/autolabel/transforms/webpage_transform.py, tests/unit/transforms/test_webpage_transform.py
Fix timeout errors on webpage scrape
Tested with new task using webpage scrape transform
=> Webpage scrape timeout errors leading to NO_TRANSFORM

src/autolabel/tasks/base.py
Deduplicate labels for multilabel response from the llm
locally
=> Deduplicate labels from the response for multilabel

src/autolabel/configs/config.py, src/autolabel/models/openai.py
Support json mode for openai models.
locally
=> Support json mode for openai models

src/autolabel/transforms/webpage_transform.py
Add HTTPS to URL when not provided
Tested locally
=> Add HTTPS to URL for webpage scrape when not provided

pyproject.toml
=> Adding sentencepiece

src/autolabel/models/refuel.py
Make refuel llm calls async
None
=> Make refuel llm calls async

src/autolabel/models/refuel.py
Increasing the timeout gives us increased throughput when making concurrent requests.
=> Increase refuel llm timeout

src/autolabel/labeler.py
=> async support for explanations

src/autolabel/tasks/attribute_extraction.py
=> Changing autolabel prompt for attribute extraction

src/autolabel/models/openai.py
Fix logit_bias for classification and openai
Tested out on task 20863a86-c470-45aa-b831-a4b7453a000e (classification task with multi token outputs) with gpt-4, gpt-4-turbo, gpt-3.5
=> Fix logit_bias for classification and openai

src/autolabel/transforms/webpage_scrape.py, tests/unit/transforms/test_webpage_scrape.py
For domains that are missing url scheme (http:// or https://), we should add it by default otherwise this results in errors.
=> Add scheme to domains that are missing it

src/autolabel/utils.py
We made the change for labeling but did not for running transforms asynchronously. This allows us to run transformations asynchronously.
=> Use single live display object when running transforms asynchronously

src/autolabel/models/__init__.py, src/autolabel/models/tgi.py, src/autolabel/schema.py
[Text Generation Inference](https://huggingface.co/docs/text-generation-inference/en/index) is a toolkit that help you run open source LLMs in your infra. Adding support for labeling your data using an LLM served as TGI.
=> Add support for Huggingface Text generation inference based LLMs

src/autolabel/few_shot/__init__.py
Changed back to VertexAIEmbeddings for Google since GoogleGenAIEmnbeddings has an issue
-Revert
=> Changed to VertexEmbedding again for few shot

src/autolabel/models/anthropic.py
Added support for haiku model from Anthropic. 
=> Added support for haiku model from Anthropic.

src/autolabel/models/anthropic.py, src/autolabel/models/google.py
Cleaned up google.py. Now it is refactored to be similar to openai.py 
- Bug fix (google bug fix)
- New Feature (added async to google and anthropic)
=> Refactored google.py to follow openai.py 

src/autolabel/labeler.py, src/autolabel/models/google.py
Added more logs to google.py to debug gemini. 
- Logs
=> Added more logs to google.py 

src/autolabel/models/google.py
Added more logs for gemini
- logs
=> Added more logs for gemini

src/autolabel/tasks/base.py, src/autolabel/tasks/classification.py, src/autolabel/tasks/question_answering.py
We need to use a different prompt template with instruction and system guidelines for models based on LLAMA.
=> Use different prompt template for llama based LLMs

src/autolabel/tasks/base.py, src/autolabel/tasks/classification.py
=> Use llama prompt schema when model_name is set

pyproject.toml
Add html2text requirement.
Missing package
=> Add html2text dependency

src/autolabel/models/tgi.py
For each element in logprob dict, we expect it to be like {"text": logprob}, however TGI models were replying with the original format returned from the server.
refuel-dev instance
=> Parse confidence scores from TGI

pyproject.toml, src/autolabel/models/google.py
Switched from GenAI -> Vertex AI so that we can support more locations and models. 
=> Switched from GenAI -> Vertex AI 

src/autolabel/models/google.py
Added support for Gemini 1.5 Pro
=> Added support for Gemini 1.5 Pro

pyproject.toml, src/autolabel/few_shot/label_selector.py, src/autolabel/few_shot/vector_store.py, src/autolabel/models/vllm.py
Allow building autolabel faster
Need to test thoroughly
=> Allow building autolabel faster

src/autolabel/models/google.py
Fix pricing for gemini models based on number of tokens.
=> Fix pricing for gemini models

src/autolabel/labeler.py
Set the tokenizer which is now needed for running refuel llm confidence
locally
=> Set the tokenizer which is now needed for running refuel llm confidence

pyproject.toml, src/autolabel/models/__init__.py, src/autolabel/models/mistral.py, src/autolabel/schema.py
=> Added support for Mistral

src/autolabel/models/mistral.py
Removed logprobs from mistral since the API always returned None. 
=> Removed logprobs from mistral

src/autolabel/models/mistral.py
Added timeout and some cleanup for mistral
- Bug Fix
=> Added timeout and some cleanup for mistral

src/autolabel/models/mistral.py
Stopped using the hugging face tokenizer for mistral
=> Stopped using the hugging face tokenizer for mistral

src/autolabel/models/google.py
Bug fix for counting tokens for vertexai
=> Bug fix for counting tokens for vertexai

src/autolabel/dataset/dataset.py
Added support for shuffling the dataset. I think it will be useful in certain cases. 
=> Added support for shuffling the dataset

examples/banking/config_banking.json, examples/banking/example_banking.ipynb, src/autolabel/models/google.py
Handling empty generations returned by Gemini 1.5 Pro API
=> Handling empty generations returned by Gemini 1.5 Pro API

src/autolabel/transforms/webpage_transform.py
=> Retry shouldn't stop if premium proxy is true

src/autolabel/data_models/transform_cache.py
=> Merge instead of Add for simultaneous updates

pyproject.toml, src/autolabel/models/openai.py
=> Adding support for v0

src/autolabel/confidence.py, src/autolabel/models/__init__.py, src/autolabel/models/refuelV2.py, src/autolabel/schema.py
=> Refuel llm 2 support in Autolabel

src/autolabel/labeler.py
Return LLM annotations with metrics for explanation generation optionally.
Tested locally
=> Optionally return LLM annotations for explanations

src/autolabel/task_chain/task_chain.py
Don't output to console by default
=> Avoid console output for task chains

src/autolabel/configs/config.py, src/autolabel/models/refuelV2.py
Passing the endpoint in the model config.
Tested locally
=> Refuel LLM: Use endpoint from config

src/autolabel/tasks/attribute_extraction.py
Return raw response for attribute extraction task
Tested locally
=> Return raw response for attribute extraction task

src/autolabel/transforms/base.py
Populate transform error column for cached values
=> Populate error column for cached transform values

src/autolabel/models/refuelV2.py
=> Support lora inference with custom endpoints

src/autolabel/tasks/attribute_extraction.py
When an LLM parsing error is encountered for attribute extraction tasks, attempt to find the valid JSON in the response text.
Tested locally for responses of the form: Based on the information, the output is {"": ""}
=> Search for valid JSON in response text on LLM Parsing error

src/autolabel/tasks/base.py
Fix output guidelines not followed error msg
Tested locally
=> Fix output guidelines not followed error msg

src/autolabel/labeler.py, src/autolabel/models/refuel.py, src/autolabel/models/refuelV2.py, src/autolabel/models/tgi.py
=> Fix tokenizer name and revision

src/autolabel/confidence.py, src/autolabel/labeler.py
=> Pass confidence endpoint in params

src/autolabel/task_chain/task_chain.py, src/autolabel/task_chain/task_chain_utils.py
Previously, the graph was not being constructed correctly and so cycle validation was not working.
Tested locally
=> Construct graph to validate task chain for cycles

src/autolabel/transforms/custom_api.py
Construct the API URL template using the given row. HTTPx library takes care of percent encoding the URL.
Tested locally
=> Construct URL given template

pyproject.toml
=> Freeze numpy version to prevent backward incompatibility with numpy v2

src/autolabel/transforms/webpage_scrape.py, src/autolabel/transforms/webpage_transform.py
Make max retries a configurable param for webpage transforms
Tested locally
=> Make max retries a configurable param for webpage transforms

src/autolabel/tasks/attribute_extraction.py
Validate attribute extraction labels list
Tested locally
=> Validate attribute extraction labels list

src/autolabel/models/openai_vision.py
=> Adding gpt4o as an option for labeling images

src/autolabel/tasks/attribute_extraction.py
=> Skip attributes that don't have any valid value in the input

src/autolabel/confidence.py, src/autolabel/labeler.py, src/autolabel/schema.py
Support for per label confidence for multilabel tasks
Tested locally
=> Support for per label confidence for multilabel tasks

src/autolabel/models/anthropic.py
=> Add 3.5 sonnet

src/autolabel/task_chain/task_chain.py
Confidence endpoint in task chain orchestrator
Tested locally
=> Confidence endpoint in task chain orchestrator

src/autolabel/configs/config.py, src/autolabel/labeler.py, src/autolabel/models/base.py, src/autolabel/models/refuelV2.py
=> Adding max context length property for models

src/autolabel/tasks/attribute_extraction.py
Output from LLM cast to string before checking label list
locally
=> Output from LLM cast to string before checking label list

src/autolabel/models/openai.py
=> Add gpt-4o-mini

benchmark/benchmark.py, src/autolabel/models/refuelV2.py
Set temperature to 0 by default
=> Set temperature to 0 by default

src/autolabel/tasks/attribute_extraction.py, src/autolabel/tasks/multilabel_classification.py
This change will validate example output dict keys in few shot examples. Any few shot example that does not have labels for all expected output fields will be filtered out during prompt construction.
Tested locally with tasks that did and did not have appropriate few shot examples with labels
=> Validate example output dict keys in few shot examples

src/autolabel/confidence.py
=> Bound check for confidence computation - imp when parsing fails

pyproject.toml, src/autolabel/tasks/attribute_extraction.py
Json5 parsing for attribute extraction
=> Json5 parsing for attribute extraction

src/autolabel/transforms/serper_api.py
Add support for num results web search parameter
- 
Tested locally with tasks with a web search enrichment
=> Add support for num results web search parameter

src/autolabel/transforms/__init__.py, src/autolabel/transforms/schema.py, src/autolabel/transforms/serper_maps.py
Map search enrichment support through the Serper API (through LangChain).
Tested with map search enrichment usage in task chain task
=> Map search enrichment support

src/autolabel/transforms/webpage_scrape.py, src/autolabel/transforms/webpage_transform.py, src/autolabel/utils.py, tests/unit/transforms/test_webpage_scrape.py
Reverts refuel-ai/autolabel#894
=> Revert "Validate webpage scrape URLs"

src/autolabel/models/openai.py, src/autolabel/models/openai_vision.py
=> Adding 4o Aug support

src/autolabel/configs/config.py, tests/assets/banking/config_banking_gpt4V.json
=> Image column name change

src/autolabel/models/openai_vision.py
=> GPT4o mini vision integration

src/autolabel/configs/config.py, src/autolabel/configs/schema.py, src/autolabel/few_shot/__init__.py, src/autolabel/few_shot/base_label_selector.py, src/autolabel/few_shot/label_selector.py, src/autolabel/few_shot/vector_store.py, src/autolabel/labeler.py, src/autolabel/task_chain/task_chain.py, src/autolabel/tasks/attribute_extraction.py
Allows using label selection if specified for attribute extraction tasks
=> Allow label selection on attribute extraction tasks

src/autolabel/labeler.py, src/autolabel/tasks/attribute_extraction.py, src/autolabel/tasks/base.py
Support generating schemas and only validating from selected labels for a label selection task
=> Support fallback label for label selection

src/autolabel/models/refuelV2.py
Don't need this now that we are moving to outlines :)
=> Remove prepare schema

src/autolabel/models/openai.py
=> Update openai gpt-4o pricing
